set (WIN_10_KITS_DIR "C:/Program Files (x86)/Windows Kits/10")
file(GLOB WIN_KITS_VERSIONS RELATIVE "${WIN_10_KITS_DIR}/lib" "${WIN_10_KITS_DIR}/lib/*")
list(FILTER WIN_KITS_VERSIONS INCLUDE REGEX "10\\.0\\.")
list(SORT WIN_KITS_VERSIONS COMPARE NATURAL ORDER DESCENDING)
list(POP_FRONT WIN_KITS_VERSIONS CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION)

set(WIN_KITS_BIN_PATH        "${WIN_10_KITS_DIR}/bin/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")
set(WIN_KITS_INCLUDE_PATH    "${WIN_10_KITS_DIR}/include/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")
set(WIN_KITS_LIB_PATH        "${WIN_10_KITS_DIR}/lib/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")


set(CMAKE_MT "${WIN_KITS_BIN_PATH}/${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}/x64/mt.exe")
set(CMAKE_RC_COMPILER "${WIN_KITS_BIN_PATH}/${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}/x64/rc.exe")
set(CMAKE_RC_FLAGS_INIT "/nologo")

set(MIDL_COMPILER "${WIN_KITS_BIN_PATH}/${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}/x64/midl.exe")
set(MDMERGE_TOOL "${WIN_KITS_BIN_PATH}/${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}/x64/mdmerge.exe")

include_directories(SYSTEM "${WIN_KITS_INCLUDE_PATH}/ucrt")
include_directories(SYSTEM "${WIN_KITS_INCLUDE_PATH}/shared")
include_directories(SYSTEM "${WIN_KITS_INCLUDE_PATH}/um")
include_directories(SYSTEM "${WIN_KITS_INCLUDE_PATH}/winrt")
include_directories(SYSTEM "${WIN_KITS_INCLUDE_PATH}/cppwinrt")
link_directories("${WIN_KITS_LIB_PATH}/ucrt/x64")
link_directories("${WIN_KITS_LIB_PATH}/um/x64")